version: '3.8'

services:
  sendmessage:
    image: ztencontacto/test-communication:sendmessage-latest
    ports:
      - "3001:3001"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "us-east-1"
      DYNAMODB_TABLE: "Messages"

  getmessages:
    image: ztencontacto/test-communication:getmessages-latest
    ports:
      - "3002:3002"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "us-east-1"
      DYNAMODB_TABLE: "Messages"

  deletemessage:
    image: ztencontacto/test-communication:deletemessage-latest
    ports:
      - "3003:3003"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "us-east-1"
      DYNAMODB_TABLE: "Messages"
