name: Deploy to EC2 on main push

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: my-dockerhub-repo/my-project
  VERSION: 3.3  # Initial version
  DOCKER_COMPOSE_FILE: docker-compose.yml

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose (Latest Version)
        run: |
          DOCKER_COMPOSE_VERSION=2.22.0
          sudo curl -L "https://github.com/docker/compose/releases/download/v$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Increment version
        id: version
        run: |
          if docker pull $IMAGE_NAME:latest; then
            CURRENT_VERSION=$(docker images --format "{{.Tag}}" $IMAGE_NAME | sort -V | tail -n1)
            NEXT_VERSION=$(echo $CURRENT_VERSION | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
          else
            NEXT_VERSION=${{ env.VERSION }}
          fi
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
          echo "Next version: $NEXT_VERSION"

      - name: Build and tag Docker image
        run: |
          docker-compose -f $DOCKER_COMPOSE_FILE build
          docker tag my-dockerhub-repo/my-project_sendmessage:latest $IMAGE_NAME:$NEXT_VERSION
          docker tag my-dockerhub-repo/my-project_sendmessage:latest $IMAGE_NAME:latest

      - name: Push image to Docker Hub
        run: |
          docker push $IMAGE_NAME:$NEXT_VERSION
          docker push $IMAGE_NAME:latest

  deploy-to-ec2:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_INSTANCE_IP }} >> ~/.ssh/known_hosts

      - name: SSH into EC2 and Deploy
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
          set -e

          # Install Docker if not installed
          if ! command -v docker &> /dev/null; then
            echo "Installing Docker..."
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
          fi

          # Install Docker Compose (Latest Version) if not installed
          if ! command -v docker-compose &> /dev/null; then
            echo "Installing Docker Compose..."
            DOCKER_COMPOSE_VERSION=2.22.0
            sudo curl -L "https://github.com/docker/compose/releases/download/v$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          # Pull the latest Docker image
          echo "Pulling the latest Docker image..."
          sudo docker pull ${{ env.IMAGE_NAME }}:latest

          # Stop and remove existing containers
          echo "Stopping and removing old containers..."
          sudo docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} down

          # Run new containers with environment variables
          echo "Starting new deployment..."
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          AWS_REGION="us-east-1" \
          DYNAMODB_TABLE="Messages" \
          sudo docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d --force-recreate
          EOF
